-- Run in Supabase SQL Editor (production) AFTER Vercel serves /article-assets/thumbnails/*.
-- Replaces all rows in public.articles with Day 0 content + self-hosted thumbnail paths.
-- Review, then: BEGIN is implicit in editor if you run the whole block; or wrap manually.

BEGIN;

DELETE FROM public.articles;

INSERT INTO public.articles (
  slug,
  title,
  url,
  source_url,
  source_name,
  source_domain,
  thumbnail_url,
  summary,
  category,
  published_at,
  is_approved,
  is_featured,
  content
)
VALUES
(
  'claude-managed-agents',
  'Claude Managed Agents',
  '/article/claude-managed-agents',
  'https://claude.com/blog/claude-managed-agents',
  'Anthropic',
  'claude.com',
  '/article-assets/thumbnails/anthropic.png',
  'Managed agent runtimes just became a product — not an engineering problem.',
  'Infra',
  now() - interval '14 days',
  true,
  false,
  E'Anthropic is shifting the focus of agent development away from models and toward execution. Claude Managed Agents packages orchestration, memory, sandboxing, and observability into a single API surface, removing the need to build custom agent infrastructure from scratch.\n\nThis introduces a new layer in the stack: agent runtimes as a service. Instead of stitching together queues, vector stores, and tool wrappers, teams can rely on a managed execution environment.\n\nAs this layer standardizes, differentiation moves up the stack. The advantage shifts toward workflows, data, and orchestration — not infrastructure.'
),
(
  'azure-mcp-server-2-0',
  'Azure MCP Server 2.0',
  '/article/azure-mcp-server-2-0',
  'https://devblogs.microsoft.com/azure-sdk/announcing-azure-mcp-server-2-0-stable-release/',
  'Microsoft',
  'devblogs.microsoft.com',
  '/article-assets/thumbnails/azure.png',
  'MCP just crossed the line from dev tool to production infrastructure.',
  'MCP',
  now() - interval '13 days',
  true,
  false,
  E'Microsoft is pushing MCP into production with a server that supports large-scale tool integration and remote deployment. This moves MCP out of local experimentation and into real infrastructure environments.\n\nThe key shift is operational. MCP servers are no longer ephemeral — they are deployed, secured, and managed like any other service.\n\nThis mirrors the evolution of APIs. Once APIs became externally exposed systems, entire ecosystems formed around them. MCP is entering that same phase.'
),
(
  'copilot-cli-copilot-mcp',
  'Copilot CLI (`copilot mcp`)',
  '/article/copilot-cli-copilot-mcp',
  'https://github.com/github/copilot-cli/releases',
  'GitHub',
  'github.com',
  '/article-assets/thumbnails/github.png',
  'MCP is becoming a core primitive in developer workflows.',
  'Tooling',
  now() - interval '12 days',
  true,
  false,
  E'Bringing MCP into the CLI marks a shift in how developers interact with tools. MCP is no longer abstract plumbing — it is something developers actively manage alongside code and environments.\n\nThis changes the structure of a toolchain. Instead of static dependencies, developers are working with dynamic, connected capabilities.\n\nSoftware development starts to look less like assembling libraries and more like composing services that agents can access.'
),
(
  'mcp-apps-in-copilot',
  'MCP Apps in Copilot',
  '/article/mcp-apps-in-copilot',
  'https://devblogs.microsoft.com/microsoft365dev/mcp-apps-now-available-in-copilot-chat/',
  'Microsoft',
  'devblogs.microsoft.com',
  '/article-assets/thumbnails/microsoft.png',
  'APIs are evolving into interactive apps inside agent interfaces.',
  'MCP',
  now() - interval '11 days',
  true,
  false,
  E'MCP Apps introduce a new interface model where tools are no longer hidden behind prompts. Instead, they surface as interactive components with UI, permissions, and workflows.\n\nThis shifts tools from backend utilities to user-facing systems inside agent environments.\n\nThe implication is that integrations need to support not just execution, but interaction — including review, approval, and visibility into what agents are doing.'
),
(
  'agentic-infrastructure',
  'Agentic Infrastructure',
  '/article/agentic-infrastructure',
  'https://vercel.com/blog/agentic-infrastructure',
  'Vercel',
  'vercel.com',
  '/article-assets/thumbnails/nextjs.png',
  'Agents are already writing and deploying real production software.',
  'Infra',
  now() - interval '10 days',
  true,
  false,
  E'Vercel reports that a significant portion of deployments are now initiated by AI agents. This marks a transition from experimentation to production usage.\n\nThe important detail is how those agents operate. They rely on APIs, CLIs, and MCP servers to interact with infrastructure.\n\nInfrastructure is no longer designed solely for humans. It is becoming an interface layer for autonomous systems.'
),
(
  'cli-mcp-agent-convergence',
  'CLI → MCP → Agent Convergence',
  '/article/cli-mcp-agent-convergence',
  NULL,
  'Industry trend',
  'agentstack.fyi',
  '/article-assets/thumbnails/osi-layers.png',
  'The next generation of tools won''t be CLI or agents — they''ll be both.',
  'Opinion',
  now() - interval '9 days',
  true,
  false,
  E'Developer tools are converging around three layers: CLI for human control, MCP for interoperability, and agents for automation.\n\nTools that began as CLI-first systems are increasingly exposing MCP interfaces, allowing agents to operate on top of them.\n\nThis is not a replacement cycle. It is a stack convergence where tools are built to serve both humans and agents simultaneously.'
),
(
  'wordpress-playground-mcp-server',
  'WordPress Playground MCP Server',
  '/article/wordpress-playground-mcp-server',
  'https://developer.wordpress.org/news/2026/04/whats-new-for-developers-april-2026/',
  'WordPress',
  'developer.wordpress.org',
  '/article-assets/thumbnails/wordpress.png',
  'A full agent loop is now possible inside a single MCP-connected environment.',
  'MCP',
  now() - interval '8 days',
  true,
  false,
  E'WordPress introduced an MCP server that enables agents to edit files, execute code, and interact with a running site.\n\nThis represents a complete loop: read, modify, execute, and observe — all within one environment.\n\nIt demonstrates how MCP can support end-to-end workflows rather than isolated tool calls.'
),
(
  'figma-agents-mcp',
  'Figma Agents + MCP',
  '/article/figma-agents-mcp',
  'https://www.figma.com/blog/the-figma-canvas-is-now-open-to-agents/',
  'Figma',
  'figma.com',
  '/article-assets/thumbnails/figma.png',
  'Design tools are becoming programmable surfaces for agents.',
  'Tooling',
  now() - interval '7 days',
  true,
  false,
  E'Figma is opening its canvas to agents via MCP, allowing direct interaction with design files. This moves design from a static artifact to an active system that agents can manipulate.\n\nThe boundary between design and code begins to collapse.\n\nAgents can now operate across both domains, making UI generation and iteration part of a continuous workflow.'
),
(
  'atlassian-confluence-mcp',
  'Atlassian Confluence + MCP',
  '/article/atlassian-confluence-mcp',
  'https://www.atlassian.com/blog/announcements/rovo-remix-3p-agents-confluence',
  'Atlassian',
  'atlassian.com',
  '/article-assets/thumbnails/atlassian.png',
  'MCP is moving into core enterprise workflows.',
  'MCP',
  now() - interval '6 days',
  true,
  false,
  E'Atlassian is embedding MCP into Confluence to power agents that transform documents into outputs like apps and presentations.\n\nThis shifts MCP from integration infrastructure to a production layer for knowledge work.\n\nInstead of retrieving information, agents are now generating deliverables directly from systems of record.'
),
(
  'supabase-mcp-exploit',
  'Supabase MCP Exploit',
  '/article/supabase-mcp-exploit',
  'https://generalanalysis.com/blog/supabase-mcp-blog',
  'General Analysis',
  'generalanalysis.com',
  '/article-assets/thumbnails/postgresql.png',
  'MCP introduces a new class of security vulnerabilities.',
  'Infra',
  now() - interval '5 days',
  true,
  false,
  E'A recent exploit demonstrates how prompt injection combined with over-permissioned MCP tools can expose sensitive data.\n\nAgents blur the line between trusted and untrusted inputs, creating new attack surfaces.\n\nSecurity in this model requires strict controls: scoped permissions, read-only defaults, audit logs, and human approval loops.'
),
(
  'google-ads-mcp-server',
  'Google Ads MCP Server',
  '/article/google-ads-mcp-server',
  'https://ads-developers.googleblog.com/2025/10/open-source-google-ads-api-mcp-server.html',
  'Google',
  'ads-developers.googleblog.com',
  '/article-assets/thumbnails/google-ads.png',
  'SaaS platforms are starting to expose MCP as a native interface layer.',
  'API',
  now() - interval '4 days',
  true,
  false,
  E'Google open-sourcing an MCP server for Ads shows how vertical platforms become accessible to agents.\n\nThis is where MCP becomes commercially meaningful — connecting agents to systems with real business impact.\n\nAdoption will be driven by high-value domains, not generic tooling.'
),
(
  'mcp-apps-fluent-api',
  'MCP Apps (Fluent API)',
  '/article/mcp-apps-fluent-api',
  'https://devblogs.microsoft.com/azure-sdk/mcp-as-easy-as-1-2-3-introducing-the-fluent-api-for-mcp-apps/',
  'Microsoft',
  'devblogs.microsoft.com',
  '/article-assets/thumbnails/vscode.png',
  'MCP tools are evolving into structured, interactive applications.',
  'MCP',
  now() - interval '3 days',
  true,
  false,
  E'Microsoft''s MCP Apps model adds UI, permissions, and policy controls to tools, making them more than simple function calls.\n\nThis introduces a new abstraction: tools as applications with behavior and interface.\n\nIt reflects a broader shift toward making agent actions observable and controllable.'
),
(
  'mcp-spec',
  'MCP Spec',
  '/article/mcp-spec',
  'https://modelcontextprotocol.io/specification',
  'MCP',
  'modelcontextprotocol.io',
  '/article-assets/thumbnails/osi-layers.png',
  'MCP defines the standard interface between agents and external systems.',
  'MCP',
  now() - interval '2 days',
  true,
  false,
  E'The MCP specification formalizes how agents interact with tools and data through a consistent protocol.\n\nStandardization reduces integration friction and enables interoperability across tools and platforms.\n\nAs adoption grows, MCP becomes the connective layer of the agent ecosystem.'
),
(
  'mcp-roadmap',
  'MCP Roadmap',
  '/article/mcp-roadmap',
  'https://modelcontextprotocol.io/development/roadmap',
  'MCP',
  'modelcontextprotocol.io',
  '/article-assets/thumbnails/microsoft.png',
  'MCP is evolving toward enterprise-grade infrastructure.',
  'MCP',
  now() - interval '1 day',
  true,
  false,
  E'The roadmap highlights priorities like scalability, authentication, governance, and auditability.\n\nThese are not developer convenience features — they are requirements for production adoption.\n\nMCP is moving from a developer tool to a system that must operate reliably inside large organizations.'
),
(
  'copilot-mcp-portability',
  'Copilot + MCP Portability',
  '/article/copilot-mcp-portability',
  'https://github.blog/changelog/',
  'GitHub',
  'github.blog',
  '/article-assets/thumbnails/github.png',
  'MCP configurations are becoming portable across tools and environments.',
  'Tooling',
  now(),
  true,
  false,
  E'GitHub is enabling MCP configurations to work across IDEs, CLIs, and agent sessions.\n\nThis reduces fragmentation and makes MCP setups reusable across contexts.\n\nThe result is a more consistent and composable developer experience.'
);

COMMIT;
