CREATE TABLE IF NOT EXISTS public.newsletter_subscribers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL UNIQUE,
  source text NOT NULL DEFAULT 'site',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT newsletter_subscribers_email_lower_chk CHECK (email = lower(email))
);

ALTER TABLE public.newsletter_subscribers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "newsletter_subscribers_insert_public" ON public.newsletter_subscribers;
CREATE POLICY "newsletter_subscribers_insert_public"
ON public.newsletter_subscribers
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "newsletter_subscribers_select_admin" ON public.newsletter_subscribers;
CREATE POLICY "newsletter_subscribers_select_admin"
ON public.newsletter_subscribers
FOR SELECT
TO authenticated
USING (
  EXISTS (SELECT 1 FROM public.admin_users u WHERE u.user_id = auth.uid())
);

GRANT INSERT ON TABLE public.newsletter_subscribers TO anon, authenticated;
GRANT SELECT ON TABLE public.newsletter_subscribers TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.newsletter_subscribers_id_seq TO anon, authenticated;
GRANT ALL ON TABLE public.newsletter_subscribers TO service_role;
